sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t tkddnjs5652/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tkddnjs5652/docker-react-app npm run test -- --coverage


